export type CampoAnamnese = {
  id: string;
  secao: string;
  label: string;
  tipo: "texto" | "textarea" | "data" | "booleano";
};

export const CAMPOS_ADULTO: CampoAnamnese[] = [
  { id: "nome_completo", secao: "Dados de identificação", label: "Nome completo", tipo: "texto" },
  { id: "data_nascimento", secao: "Dados de identificação", label: "Data de nascimento", tipo: "data" },
  { id: "sexo", secao: "Dados de identificação", label: "Sexo", tipo: "texto" },
  { id: "endereco", secao: "Dados de identificação", label: "Endereço", tipo: "texto" },
  { id: "telefone", secao: "Dados de identificação", label: "Telefone", tipo: "texto" },
  { id: "responsavel", secao: "Dados de identificação", label: "Responsável (se aplicável)", tipo: "texto" },
  { id: "profissao", secao: "Dados de identificação", label: "Profissão", tipo: "texto" },
  { id: "inicio_sintomas", secao: "História da doença atual", label: "Início dos sintomas", tipo: "textarea" },
  { id: "fatores_desencadeantes", secao: "História da doença atual", label: "Fatores desencadeantes", tipo: "textarea" },
  { id: "frequencia_intensidade", secao: "História da doença atual", label: "Frequência e intensidade", tipo: "textarea" },
  { id: "tratamentos_anteriores", secao: "História da doença atual", label: "Tratamentos anteriores", tipo: "textarea" },
  { id: "avc", secao: "Histórico médico — neurológico", label: "AVC", tipo: "booleano" },
  { id: "avc_detalhe", secao: "Histórico médico — neurológico", label: "AVC — quando? sequelas?", tipo: "texto" },
  { id: "traumatismo_craniano", secao: "Histórico médico — neurológico", label: "Traumatismo craniano", tipo: "booleano" },
  { id: "traumatismo_detalhe", secao: "Histórico médico — neurológico", label: "Traumatismo craniano — quando?", tipo: "texto" },
  { id: "epilepsia", secao: "Histórico médico — neurológico", label: "Epilepsia/Convulsões", tipo: "booleano" },
  { id: "epilepsia_detalhe", secao: "Histórico médico — neurológico", label: "Epilepsia/Convulsões — última crise", tipo: "texto" },
  { id: "tumores_cerebrais", secao: "Histórico médico — neurológico", label: "Tumores cerebrais", tipo: "booleano" },
  { id: "enxaquecas_frequentes", secao: "Histórico médico — neurológico", label: "Enxaquecas frequentes", tipo: "booleano" },
  { id: "doenca_neurodegenerativa", secao: "Histórico médico — neurológico", label: "Doença neurodegenerativa", tipo: "booleano" },
  { id: "doenca_neurodegenerativa_detalhe", secao: "Histórico médico — neurológico", label: "Doença neurodegenerativa — qual?", tipo: "texto" },
  { id: "infarto", secao: "Histórico médico — cardíaco", label: "Infarto", tipo: "booleano" },
  { id: "infarto_detalhe", secao: "Histórico médico — cardíaco", label: "Infarto — quando?", tipo: "texto" },
  { id: "arritmia", secao: "Histórico médico — cardíaco", label: "Arritmia", tipo: "booleano" },
  { id: "marca_passo", secao: "Histórico médico — cardíaco", label: "Marca-passo", tipo: "booleano" },
  { id: "cirurgias", secao: "Histórico médico — cirurgias", label: "Já realizou cirurgias? Quais?", tipo: "textarea" },
  { id: "implantes_metalicos", secao: "Histórico médico — cirurgias", label: "Implantes metálicos na cabeça/face?", tipo: "booleano" },
  { id: "implante_coclear", secao: "Histórico médico — cirurgias", label: "Implante coclear?", tipo: "booleano" },
  { id: "internacoes", secao: "Histórico médico", label: "Já foi internado? Quando e por qual motivo?", tipo: "textarea" },
  { id: "medicamentos_atuais", secao: "Histórico médico", label: "Quais medicamentos usa atualmente?", tipo: "textarea" },
  { id: "alergias", secao: "Histórico médico", label: "Possui alergia? Qual?", tipo: "textarea" },
  { id: "depressao", secao: "Histórico médico — psiquiátrico", label: "Depressão", tipo: "booleano" },
  { id: "ansiedade", secao: "Histórico médico — psiquiátrico", label: "Ansiedade", tipo: "booleano" },
  { id: "tea", secao: "Histórico médico — psiquiátrico", label: "TEA", tipo: "booleano" },
  { id: "tdah", secao: "Histórico médico — psiquiátrico", label: "TDAH", tipo: "booleano" },
  { id: "outra_condicao_psiquiatrica", secao: "Histórico médico — psiquiátrico", label: "Outra condição psiquiátrica", tipo: "texto" },
  { id: "internacoes_psiquiatricas", secao: "Histórico médico — psiquiátrico", label: "Internações psiquiátricas", tipo: "textarea" },
  { id: "doencas_neurologicas_familia", secao: "Histórico familiar", label: "Doenças neurológicas na família (AVC, epilepsia)", tipo: "textarea" },
  { id: "transtornos_psiquiatricos_familia", secao: "Histórico familiar", label: "Transtornos psiquiátricos na família", tipo: "textarea" },
  { id: "febre_infeccao", secao: "Condições atuais", label: "Febre ou infecção?", tipo: "texto" },
  { id: "feridas_couro_cabeludo", secao: "Condições atuais", label: "Feridas no couro cabeludo?", tipo: "texto" },
  { id: "esta_gravida", secao: "Condições atuais", label: "Está grávida?", tipo: "texto" },
  { id: "dor_cabeca_hoje", secao: "Condições atuais", label: "Dor de cabeça intensa hoje?", tipo: "texto" },
  { id: "qualidade_sono", secao: "Hábitos de vida", label: "Qualidade do sono", tipo: "texto" },
  { id: "uso_alcool", secao: "Hábitos de vida", label: "Uso de álcool", tipo: "booleano" },
  { id: "uso_alcool_frequencia", secao: "Hábitos de vida", label: "Uso de álcool — frequência", tipo: "texto" },
  { id: "tabagismo", secao: "Hábitos de vida", label: "Tabagismo", tipo: "booleano" },
  { id: "tabagismo_quantidade", secao: "Hábitos de vida", label: "Tabagismo — quantidade por dia", tipo: "texto" },
  { id: "uso_drogas_ilicitas", secao: "Hábitos de vida", label: "Uso de drogas ilícitas", tipo: "texto" },
  { id: "epilepsia_ativa", secao: "Contraindicações", label: "Epilepsia ativa?", tipo: "booleano" },
  { id: "implantes_metalicos_cabeca", secao: "Contraindicações", label: "Implantes metálicos na cabeça?", tipo: "booleano" },
  { id: "lesoes_couro_cabeludo", secao: "Contraindicações", label: "Lesões ou infecções no couro cabeludo?", tipo: "booleano" },
  { id: "funcao_a_trabalhar", secao: "Objetivo do tratamento", label: "Função a ser trabalhada (atenção, memória, linguagem, humor, controle motor, etc.)", tipo: "texto" },
  { id: "ja_fez_tdcs", secao: "Objetivo do tratamento", label: "Já realizou tDCS antes? Como foi?", tipo: "textarea" },
];

export const CAMPOS_INFANTIL: CampoAnamnese[] = [
  { id: "nome_crianca", secao: "Dados de identificação", label: "Nome completo da criança", tipo: "texto" },
  { id: "data_nascimento", secao: "Dados de identificação", label: "Data de nascimento", tipo: "data" },
  { id: "sexo", secao: "Dados de identificação", label: "Sexo", tipo: "texto" },
  { id: "nome_responsavel", secao: "Dados de identificação", label: "Nome do responsável", tipo: "texto" },
  { id: "telefone_contato", secao: "Dados de identificação", label: "Telefone para contato", tipo: "texto" },
  { id: "endereco", secao: "Dados de identificação", label: "Endereço", tipo: "texto" },
  { id: "escola", secao: "Dados de identificação", label: "Escola", tipo: "texto" },
  { id: "ano_escolar", secao: "Dados de identificação", label: "Ano escolar", tipo: "texto" },
  { id: "profissionais_acompanham", secao: "Dados de identificação", label: "Profissionais que acompanham a criança", tipo: "textarea" },
  { id: "dificuldade_preocupa_familia", secao: "Queixa principal", label: "Qual a principal dificuldade ou comportamento que preocupa a família?", tipo: "textarea" },
  { id: "motivo_busca_tdcs", secao: "Queixa principal", label: "O que motivou a busca pela aplicação do tDCS?", tipo: "textarea" },
  { id: "gestacao_parto", secao: "Desenvolvimento", label: "Como foi a gestação e o parto? (prematuridade, intercorrências, medicamentos)", tipo: "textarea" },
  { id: "internacao_uti_neonatal", secao: "Desenvolvimento", label: "Houve internação na UTI neonatal?", tipo: "texto" },
  { id: "marcos_motores", secao: "Desenvolvimento", label: "Quando começou a sentar, engatinhar e andar?", tipo: "texto" },
  { id: "primeiras_palavras", secao: "Desenvolvimento", label: "Quando falou as primeiras palavras?", tipo: "texto" },
  { id: "fala_comunicacao_atual", secao: "Desenvolvimento", label: "Como está a fala e a comunicação atualmente?", tipo: "textarea" },
  { id: "usa_frases_conversas", secao: "Desenvolvimento", label: "A criança usa frases? Consegue manter conversas?", tipo: "texto" },
  { id: "diagnostico_tea", secao: "Condições médicas", label: "TEA", tipo: "booleano" },
  { id: "diagnostico_tdah", secao: "Condições médicas", label: "TDAH", tipo: "booleano" },
  { id: "diagnostico_atraso_linguagem", secao: "Condições médicas", label: "Atraso de linguagem", tipo: "booleano" },
  { id: "diagnostico_apraxia_fala", secao: "Condições médicas", label: "Apraxia de fala", tipo: "booleano" },
  { id: "diagnostico_epilepsia", secao: "Condições médicas", label: "Epilepsia", tipo: "booleano" },
  { id: "diagnostico_outro", secao: "Condições médicas", label: "Outro diagnóstico", tipo: "texto" },
  { id: "episodio_convulsao", secao: "Condições médicas", label: "Algum episódio de convulsão?", tipo: "booleano" },
  { id: "convulsao_ultima_crise", secao: "Condições médicas", label: "Convulsão — última crise", tipo: "texto" },
  { id: "historico_avc_tce_lesoes", secao: "Condições médicas", label: "Histórico de AVC, traumatismo craniano ou lesões cerebrais?", tipo: "textarea" },
  { id: "cirurgias", secao: "Condições médicas", label: "Já realizou cirurgias? Quais?", tipo: "textarea" },
  { id: "internacoes", secao: "Condições médicas", label: "Já ficou internado? Por qual motivo?", tipo: "textarea" },
  { id: "medicamentos_atuais", secao: "Condições médicas", label: "Faz uso de algum medicamento atualmente? Quais? Horários?", tipo: "textarea" },
  { id: "alergias", secao: "Condições médicas", label: "Tem alergia a algum medicamento ou material?", tipo: "textarea" },
  { id: "crianca_fala", secao: "Fono e psicológico", label: "A criança fala?", tipo: "booleano" },
  { id: "usa_comunicacao_alternativa", secao: "Fono e psicológico", label: "Usa Comunicação Alternativa (figuras, tablet)?", tipo: "texto" },
  { id: "compreensao_ordens_simples", secao: "Fono e psicológico", label: "Como é a compreensão de ordens simples (ex: \"traz a bola\")?", tipo: "textarea" },
  { id: "interage_outras_pessoas", secao: "Fono e psicológico", label: "A criança interage com outras pessoas? (olha nos olhos, brinca junto)", tipo: "textarea" },
  { id: "comportamentos_repetitivos", secao: "Fono e psicológico", label: "Tem comportamentos repetitivos (balanço, bater as mãos)?", tipo: "textarea" },
  { id: "dificuldades_sensoriais", secao: "Fono e psicológico", label: "Tem dificuldades com barulhos, texturas ou sabores?", tipo: "textarea" },
  { id: "sono", secao: "Fono e psicológico", label: "Como é o sono? Dorme bem?", tipo: "textarea" },
  { id: "alimentacao", secao: "Fono e psicológico", label: "Como é a alimentação? Aceita alimentos variados?", tipo: "textarea" },
  { id: "comportamento_escola", secao: "Rotina e comportamento", label: "Frequenta escola? Como se comporta lá?", tipo: "textarea" },
  { id: "atencao_atividades", secao: "Rotina e comportamento", label: "Consegue manter atenção em atividades? Por quanto tempo?", tipo: "textarea" },
  { id: "crises_irritacao", secao: "Rotina e comportamento", label: "Tem crises de irritação? O que desencadeia?", tipo: "textarea" },
  { id: "brincadeiras_favoritas", secao: "Rotina e comportamento", label: "O que a criança gosta de fazer (brincadeiras favoritas)?", tipo: "textarea" },
  { id: "funcao_atencao", secao: "Objetivo do tratamento", label: "Atenção", tipo: "booleano" },
  { id: "funcao_controle_impulsos", secao: "Objetivo do tratamento", label: "Controle de impulsos", tipo: "booleano" },
  { id: "funcao_linguagem_fala", secao: "Objetivo do tratamento", label: "Linguagem e fala", tipo: "booleano" },
  { id: "funcao_comportamento", secao: "Objetivo do tratamento", label: "Comportamento", tipo: "booleano" },
  { id: "funcao_memoria", secao: "Objetivo do tratamento", label: "Memória", tipo: "booleano" },
  { id: "funcao_humor", secao: "Objetivo do tratamento", label: "Humor", tipo: "booleano" },
  { id: "ja_fez_tdcs_crianca", secao: "Objetivo do tratamento", label: "A criança já fez tDCS antes? Como foi a experiência?", tipo: "textarea" },
];
